apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

resources:
  - "https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml"
  - ../../bootstrap/overlays/local
patchesStrategicMerge:
  - "argocd-ingress.yml"
  - "prometheus.yml"
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: test-selfsigned
      - op: remove
        path: /spec/acme
      - op: add
        path: /spec/selfSigned
        value: {}
    target:
      kind: ClusterIssuer
      name: letsencrypt-prod
