apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://github.com/cert-manager/cert-manager/releases/download/v1.8.1/cert-manager.yaml"
  - "cluster-issuer.yml"
  - "argocd-ingress.yml"
  - "blog-repo.yml"
  - "prometheus.yml"
  - "prometheus-crds.yml"
